/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KhachHangIndexRouteImport } from './routes/khach-hang/index'
import { Route as KhachHangThemKhachHangRouteImport } from './routes/khach-hang/them-khach-hang'
import { Route as TrangChuIndexRouteImport } from './routes/trang-chu/index'
import { Route as TrangChuCapNhatKetQuaRouteImport } from './routes/trang-chu/cap-nhat-ket-qua'
import { Route as KhachHangCustomerIdIndexRouteImport } from './routes/khach-hang/$customerId/index'
import { Route as KhachHangCustomerIdDuChuanRouteImport } from './routes/khach-hang/$customerId/du-chuan'
import { Route as KhachHangCustomerIdTinNhanRouteImport } from './routes/khach-hang/$customerId/tin-nhan'
import { Route as KhachHangCustomerIdOrderIdChiTietRouteImport } from './routes/khach-hang/$customerId/$orderId.chi-tiet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangIndexRoute = KhachHangIndexRouteImport.update({
  id: '/khach-hang/',
  path: '/khach-hang/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangThemKhachHangRoute = KhachHangThemKhachHangRouteImport.update({
  id: '/khach-hang/them-khach-hang',
  path: '/khach-hang/them-khach-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const TrangChuIndexRoute = TrangChuIndexRouteImport.update({
  id: '/trang-chu/',
  path: '/trang-chu/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrangChuCapNhatKetQuaRoute = TrangChuCapNhatKetQuaRouteImport.update({
  id: '/trang-chu/cap-nhat-ket-qua',
  path: '/trang-chu/cap-nhat-ket-qua',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangCustomerIdIndexRoute =
  KhachHangCustomerIdIndexRouteImport.update({
    id: '/khach-hang/$customerId/',
    path: '/khach-hang/$customerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const KhachHangCustomerIdDuChuanRoute =
  KhachHangCustomerIdDuChuanRouteImport.update({
    id: '/khach-hang/$customerId/du-chuan',
    path: '/khach-hang/$customerId/du-chuan',
    getParentRoute: () => rootRouteImport,
  } as any)
const KhachHangCustomerIdTinNhanRoute =
  KhachHangCustomerIdTinNhanRouteImport.update({
    id: '/khach-hang/$customerId/tin-nhan',
    path: '/khach-hang/$customerId/tin-nhan',
    getParentRoute: () => rootRouteImport,
  } as any)
const KhachHangCustomerIdOrderIdChiTietRoute =
  KhachHangCustomerIdOrderIdChiTietRouteImport.update({
    id: '/khach-hang/$customerId/$orderId/chi-tiet',
    path: '/khach-hang/$customerId/$orderId/chi-tiet',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/khach-hang/them-khach-hang': typeof KhachHangThemKhachHangRoute
  '/trang-chu/cap-nhat-ket-qua': typeof TrangChuCapNhatKetQuaRoute
  '/khach-hang/': typeof KhachHangIndexRoute
  '/trang-chu/': typeof TrangChuIndexRoute
  '/khach-hang/$customerId/du-chuan': typeof KhachHangCustomerIdDuChuanRoute
  '/khach-hang/$customerId/tin-nhan': typeof KhachHangCustomerIdTinNhanRoute
  '/khach-hang/$customerId/': typeof KhachHangCustomerIdIndexRoute
  '/khach-hang/$customerId/$orderId/chi-tiet': typeof KhachHangCustomerIdOrderIdChiTietRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/khach-hang/them-khach-hang': typeof KhachHangThemKhachHangRoute
  '/trang-chu/cap-nhat-ket-qua': typeof TrangChuCapNhatKetQuaRoute
  '/khach-hang': typeof KhachHangIndexRoute
  '/trang-chu': typeof TrangChuIndexRoute
  '/khach-hang/$customerId/du-chuan': typeof KhachHangCustomerIdDuChuanRoute
  '/khach-hang/$customerId/tin-nhan': typeof KhachHangCustomerIdTinNhanRoute
  '/khach-hang/$customerId': typeof KhachHangCustomerIdIndexRoute
  '/khach-hang/$customerId/$orderId/chi-tiet': typeof KhachHangCustomerIdOrderIdChiTietRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/khach-hang/them-khach-hang': typeof KhachHangThemKhachHangRoute
  '/trang-chu/cap-nhat-ket-qua': typeof TrangChuCapNhatKetQuaRoute
  '/khach-hang/': typeof KhachHangIndexRoute
  '/trang-chu/': typeof TrangChuIndexRoute
  '/khach-hang/$customerId/du-chuan': typeof KhachHangCustomerIdDuChuanRoute
  '/khach-hang/$customerId/tin-nhan': typeof KhachHangCustomerIdTinNhanRoute
  '/khach-hang/$customerId/': typeof KhachHangCustomerIdIndexRoute
  '/khach-hang/$customerId/$orderId/chi-tiet': typeof KhachHangCustomerIdOrderIdChiTietRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/khach-hang/them-khach-hang'
    | '/trang-chu/cap-nhat-ket-qua'
    | '/khach-hang/'
    | '/trang-chu/'
    | '/khach-hang/$customerId/du-chuan'
    | '/khach-hang/$customerId/tin-nhan'
    | '/khach-hang/$customerId/'
    | '/khach-hang/$customerId/$orderId/chi-tiet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/khach-hang/them-khach-hang'
    | '/trang-chu/cap-nhat-ket-qua'
    | '/khach-hang'
    | '/trang-chu'
    | '/khach-hang/$customerId/du-chuan'
    | '/khach-hang/$customerId/tin-nhan'
    | '/khach-hang/$customerId'
    | '/khach-hang/$customerId/$orderId/chi-tiet'
  id:
    | '__root__'
    | '/'
    | '/khach-hang/them-khach-hang'
    | '/trang-chu/cap-nhat-ket-qua'
    | '/khach-hang/'
    | '/trang-chu/'
    | '/khach-hang/$customerId/du-chuan'
    | '/khach-hang/$customerId/tin-nhan'
    | '/khach-hang/$customerId/'
    | '/khach-hang/$customerId/$orderId/chi-tiet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KhachHangThemKhachHangRoute: typeof KhachHangThemKhachHangRoute
  TrangChuCapNhatKetQuaRoute: typeof TrangChuCapNhatKetQuaRoute
  KhachHangIndexRoute: typeof KhachHangIndexRoute
  TrangChuIndexRoute: typeof TrangChuIndexRoute
  KhachHangCustomerIdDuChuanRoute: typeof KhachHangCustomerIdDuChuanRoute
  KhachHangCustomerIdTinNhanRoute: typeof KhachHangCustomerIdTinNhanRoute
  KhachHangCustomerIdIndexRoute: typeof KhachHangCustomerIdIndexRoute
  KhachHangCustomerIdOrderIdChiTietRoute: typeof KhachHangCustomerIdOrderIdChiTietRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/': {
      id: '/khach-hang/'
      path: '/khach-hang'
      fullPath: '/khach-hang/'
      preLoaderRoute: typeof KhachHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/them-khach-hang': {
      id: '/khach-hang/them-khach-hang'
      path: '/khach-hang/them-khach-hang'
      fullPath: '/khach-hang/them-khach-hang'
      preLoaderRoute: typeof KhachHangThemKhachHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trang-chu/': {
      id: '/trang-chu/'
      path: '/trang-chu'
      fullPath: '/trang-chu/'
      preLoaderRoute: typeof TrangChuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trang-chu/cap-nhat-ket-qua': {
      id: '/trang-chu/cap-nhat-ket-qua'
      path: '/trang-chu/cap-nhat-ket-qua'
      fullPath: '/trang-chu/cap-nhat-ket-qua'
      preLoaderRoute: typeof TrangChuCapNhatKetQuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/$customerId/': {
      id: '/khach-hang/$customerId/'
      path: '/khach-hang/$customerId'
      fullPath: '/khach-hang/$customerId/'
      preLoaderRoute: typeof KhachHangCustomerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/$customerId/du-chuan': {
      id: '/khach-hang/$customerId/du-chuan'
      path: '/khach-hang/$customerId/du-chuan'
      fullPath: '/khach-hang/$customerId/du-chuan'
      preLoaderRoute: typeof KhachHangCustomerIdDuChuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/$customerId/tin-nhan': {
      id: '/khach-hang/$customerId/tin-nhan'
      path: '/khach-hang/$customerId/tin-nhan'
      fullPath: '/khach-hang/$customerId/tin-nhan'
      preLoaderRoute: typeof KhachHangCustomerIdTinNhanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/$customerId/$orderId/chi-tiet': {
      id: '/khach-hang/$customerId/$orderId/chi-tiet'
      path: '/khach-hang/$customerId/$orderId/chi-tiet'
      fullPath: '/khach-hang/$customerId/$orderId/chi-tiet'
      preLoaderRoute: typeof KhachHangCustomerIdOrderIdChiTietRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KhachHangThemKhachHangRoute: KhachHangThemKhachHangRoute,
  TrangChuCapNhatKetQuaRoute: TrangChuCapNhatKetQuaRoute,
  KhachHangIndexRoute: KhachHangIndexRoute,
  TrangChuIndexRoute: TrangChuIndexRoute,
  KhachHangCustomerIdDuChuanRoute: KhachHangCustomerIdDuChuanRoute,
  KhachHangCustomerIdTinNhanRoute: KhachHangCustomerIdTinNhanRoute,
  KhachHangCustomerIdIndexRoute: KhachHangCustomerIdIndexRoute,
  KhachHangCustomerIdOrderIdChiTietRoute:
    KhachHangCustomerIdOrderIdChiTietRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
