/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KhachHangIndexRouteImport } from './routes/khach-hang/index'
import { Route as KhachHangCustomerIdRouteImport } from './routes/khach-hang/$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangIndexRoute = KhachHangIndexRouteImport.update({
  id: '/khach-hang/',
  path: '/khach-hang/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangCustomerIdRoute = KhachHangCustomerIdRouteImport.update({
  id: '/khach-hang/$customerId',
  path: '/khach-hang/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/khach-hang/$customerId': typeof KhachHangCustomerIdRoute
  '/khach-hang/': typeof KhachHangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/khach-hang/$customerId': typeof KhachHangCustomerIdRoute
  '/khach-hang': typeof KhachHangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/khach-hang/$customerId': typeof KhachHangCustomerIdRoute
  '/khach-hang/': typeof KhachHangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/khach-hang/$customerId' | '/khach-hang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/khach-hang/$customerId' | '/khach-hang'
  id: '__root__' | '/' | '/khach-hang/$customerId' | '/khach-hang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KhachHangCustomerIdRoute: typeof KhachHangCustomerIdRoute
  KhachHangIndexRoute: typeof KhachHangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/': {
      id: '/khach-hang/'
      path: '/khach-hang'
      fullPath: '/khach-hang/'
      preLoaderRoute: typeof KhachHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang/$customerId': {
      id: '/khach-hang/$customerId'
      path: '/khach-hang/$customerId'
      fullPath: '/khach-hang/$customerId'
      preLoaderRoute: typeof KhachHangCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KhachHangCustomerIdRoute: KhachHangCustomerIdRoute,
  KhachHangIndexRoute: KhachHangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
